---
name: quran_hadith
description: Qur'an & Hadith
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  intl: null
  font_awesome_flutter: null
  bubble_tab_indicator: null
  shimmer: ^1.1.2
  shared_preferences: ^0.5.12+4
  auto_size_text: null
  url_launcher: null
  lottie: null
  provider:
  get:
  adaptive_breakpoints: ^0.0.2
  audioplayers: ^0.10.1
  package_info: null
  flutter_animated_dialog: any
  scroll_to_index: any
  animations: ^1.1.2
  popover: ^0.0.4
  animated_theme_switcher: ^1.0.6
#  platform_device_id:
#  process_run:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher-Bold.ttf
        - asset: assets/fonts/Philosopher-Regular.ttf
        - asset: assets/fonts/Philosopher-Italic.ttf
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-Regular.ttf
    - family: Quattrocento
      fonts:
        - asset: assets/fonts/Quattrocento-Regular.ttf
        - asset: assets/fonts/Quattrocento-Bold.ttf
    - family: Quran 1
      fonts:
        - asset: assets/fonts/ar-Quran1.ttf
